import 'package:flutter/material.dart';
import 'package:joufflu/joufflu.dart';

/// A named palette selectable from the theme customizer, same set as the WPF gallery.
class ThemePreset {
  const ThemePreset(this.name, this.colors);

  final String name;
  final JouffluColors colors;
}

final presets = [
  ThemePreset('Light', JouffluColors.light),
  ThemePreset('Dark', JouffluColors.dark),
  ThemePreset(
    'Corporate',
    JouffluColors({
      JouffluColor.foreground: const Color(0xFF181A2A),
      JouffluColor.foreground100: const Color(0xFF696A75),
      JouffluColor.foreground200: const Color(0xFF97989F),
      JouffluColor.border: const Color(0xFFE5E9F0),
      JouffluColor.border100: const Color(0xFFF2F4F8),
      JouffluColor.background: const Color(0xFFFFFFFF),
      JouffluColor.background100: const Color(0xFFF7F9FC),
      JouffluColor.background200: const Color(0xFFEEF2F6),
      JouffluColor.primary: const Color(0xFF4B6BFB),
      JouffluColor.primary100: const Color(0xFF405BD5),
      JouffluColor.primaryContent: const Color(0xFFFFFFFF),
      JouffluColor.secondary: const Color(0xFF7B92B2),
      JouffluColor.secondary100: const Color(0xFF697C97),
      JouffluColor.secondaryContent: const Color(0xFFFFFFFF),
      JouffluColor.success: const Color(0xFF36D399),
      JouffluColor.success100: const Color(0xFF2EB382),
      JouffluColor.successContent: const Color(0xFF04160B),
      JouffluColor.info: const Color(0xFF3ABFF8),
      JouffluColor.info100: const Color(0xFF31A2D3),
      JouffluColor.infoContent: const Color(0xFF06222E),
      JouffluColor.warning: const Color(0xFFFBBD23),
      JouffluColor.warning100: const Color(0xFFD5A11E),
      JouffluColor.warningContent: const Color(0xFF3A2C00),
      JouffluColor.danger: const Color(0xFFF87272),
      JouffluColor.danger100: const Color(0xFFD36161),
      JouffluColor.dangerContent: const Color(0xFF3A0E0E),
    }),
  ),
  ThemePreset(
    'Cupcake',
    JouffluColors({
      JouffluColor.foreground: const Color(0xFF291334),
      JouffluColor.foreground100: const Color(0xFF726378),
      JouffluColor.foreground200: const Color(0xFF9C909E),
      JouffluColor.border: const Color(0xFFDCD4CD),
      JouffluColor.border100: const Color(0xFFEBE6E1),
      JouffluColor.background: const Color(0xFFFAF7F5),
      JouffluColor.background100: const Color(0xFFEFEAE6),
      JouffluColor.background200: const Color(0xFFE7E2DF),
      JouffluColor.primary: const Color(0xFF65C3C8),
      JouffluColor.primary100: const Color(0xFF56A6AA),
      JouffluColor.primaryContent: const Color(0xFF093A3E),
      JouffluColor.secondary: const Color(0xFFEF9FBC),
      JouffluColor.secondary100: const Color(0xFFCB87A0),
      JouffluColor.secondaryContent: const Color(0xFF45162E),
      JouffluColor.success: const Color(0xFF00B795),
      JouffluColor.success100: const Color(0xFF009C7F),
      JouffluColor.successContent: const Color(0xFF003A2E),
      JouffluColor.info: const Color(0xFFEEAF3A),
      JouffluColor.info100: const Color(0xFFCA9531),
      JouffluColor.infoContent: const Color(0xFF3A2A06),
      JouffluColor.warning: const Color(0xFFF3CC30),
      JouffluColor.warning100: const Color(0xFFCFAD29),
      JouffluColor.warningContent: const Color(0xFF3A3206),
      JouffluColor.danger: const Color(0xFFFF6F70),
      JouffluColor.danger100: const Color(0xFFD95E5F),
      JouffluColor.dangerContent: const Color(0xFF3A0E0E),
    }),
  ),
  ThemePreset(
    'Dracula',
    JouffluColors({
      JouffluColor.foreground: const Color(0xFFF8F8F2),
      JouffluColor.foreground100: const Color(0xFFAFB0B0),
      JouffluColor.foreground200: const Color(0xFF86878B),
      JouffluColor.border: const Color(0xFF44475A),
      JouffluColor.border100: const Color(0xFF363848),
      JouffluColor.background: const Color(0xFF282A36),
      JouffluColor.background100: const Color(0xFF343746),
      JouffluColor.background200: const Color(0xFF424458),
      JouffluColor.primary: const Color(0xFFFF79C6),
      JouffluColor.primary100: const Color(0xFFD967A8),
      JouffluColor.primaryContent: const Color(0xFF1A1423),
      JouffluColor.secondary: const Color(0xFFBD93F9),
      JouffluColor.secondary100: const Color(0xFFA17DD4),
      JouffluColor.secondaryContent: const Color(0xFF1A1423),
      JouffluColor.success: const Color(0xFF50FA7B),
      JouffluColor.success100: const Color(0xFF44D469),
      JouffluColor.successContent: const Color(0xFF05260F),
      JouffluColor.info: const Color(0xFF8BE9FD),
      JouffluColor.info100: const Color(0xFF76C6D7),
      JouffluColor.infoContent: const Color(0xFF06222A),
      JouffluColor.warning: const Color(0xFFF1FA8C),
      JouffluColor.warning100: const Color(0xFFCDD477),
      JouffluColor.warningContent: const Color(0xFF2E2E05),
      JouffluColor.danger: const Color(0xFFFF5555),
      JouffluColor.danger100: const Color(0xFFD94848),
      JouffluColor.dangerContent: const Color(0xFF2E0707),
    }),
  ),
  ThemePreset(
    'Emerald',
    JouffluColors({
      JouffluColor.foreground: const Color(0xFF333C4D),
      JouffluColor.foreground100: const Color(0xFF7A808B),
      JouffluColor.foreground200: const Color(0xFFA3A7AF),
      JouffluColor.border: const Color(0xFFE5E7EB),
      JouffluColor.border100: const Color(0xFFF2F3F5),
      JouffluColor.background: const Color(0xFFFFFFFF),
      JouffluColor.background100: const Color(0xFFF4F6F8),
      JouffluColor.background200: const Color(0xFFE5E7EB),
      JouffluColor.primary: const Color(0xFF66CC8A),
      JouffluColor.primary100: const Color(0xFF57AD75),
      JouffluColor.primaryContent: const Color(0xFF04160B),
      JouffluColor.secondary: const Color(0xFF377CFB),
      JouffluColor.secondary100: const Color(0xFF2F69D5),
      JouffluColor.secondaryContent: const Color(0xFFFFFFFF),
      JouffluColor.success: const Color(0xFF00A96E),
      JouffluColor.success100: const Color(0xFF00905E),
      JouffluColor.successContent: const Color(0xFFFFFFFF),
      JouffluColor.info: const Color(0xFFF68067),
      JouffluColor.info100: const Color(0xFFD16D58),
      JouffluColor.infoContent: const Color(0xFF2A0F08),
      JouffluColor.warning: const Color(0xFFFFBE00),
      JouffluColor.warning100: const Color(0xFFD9A200),
      JouffluColor.warningContent: const Color(0xFF3A2C00),
      JouffluColor.danger: const Color(0xFFF87272),
      JouffluColor.danger100: const Color(0xFFD36161),
      JouffluColor.dangerContent: const Color(0xFF3A0E0E),
    }),
  ),
  ThemePreset(
    'Nord',
    JouffluColors({
      JouffluColor.foreground: const Color(0xFF2E3440),
      JouffluColor.foreground100: const Color(0xFF70757F),
      JouffluColor.foreground200: const Color(0xFF969BA3),
      JouffluColor.border: const Color(0xFFD8DEE9),
      JouffluColor.border100: const Color(0xFFE2E6EE),
      JouffluColor.background: const Color(0xFFECEFF4),
      JouffluColor.background100: const Color(0xFFE5E9F0),
      JouffluColor.background200: const Color(0xFFD8DEE9),
      JouffluColor.primary: const Color(0xFF5E81AC),
      JouffluColor.primary100: const Color(0xFF506E92),
      JouffluColor.primaryContent: const Color(0xFFFFFFFF),
      JouffluColor.secondary: const Color(0xFF81A1C1),
      JouffluColor.secondary100: const Color(0xFF6E89A4),
      JouffluColor.secondaryContent: const Color(0xFF10151D),
      JouffluColor.success: const Color(0xFFA3BE8C),
      JouffluColor.success100: const Color(0xFF8BA277),
      JouffluColor.successContent: const Color(0xFF10201A),
      JouffluColor.info: const Color(0xFF88C0D0),
      JouffluColor.info100: const Color(0xFF74A3B1),
      JouffluColor.infoContent: const Color(0xFF0A2027),
      JouffluColor.warning: const Color(0xFFEBCB8B),
      JouffluColor.warning100: const Color(0xFFC8AD76),
      JouffluColor.warningContent: const Color(0xFF2E2606),
      JouffluColor.danger: const Color(0xFFBF616A),
      JouffluColor.danger100: const Color(0xFFA2525A),
      JouffluColor.dangerContent: const Color(0xFFFFFFFF),
    }),
  ),
  ThemePreset(
    'Ocean',
    JouffluColors({
      JouffluColor.foreground: const Color(0xFFE6F1F5),
      JouffluColor.foreground100: const Color(0xFF9FBECB),
      JouffluColor.foreground200: const Color(0xFF7FA6B4),
      JouffluColor.border: const Color(0xFF1B4250),
      JouffluColor.border100: const Color(0xFF2A5A6B),
      JouffluColor.background: const Color(0xFF0B1E27),
      JouffluColor.background100: const Color(0xFF12303B),
      JouffluColor.background200: const Color(0xFF1B4250),
      JouffluColor.primary: const Color(0xFF2DD4BF),
      JouffluColor.primary100: const Color(0xFF26B8A6),
      JouffluColor.primaryContent: const Color(0xFF04211D),
      JouffluColor.secondary: const Color(0xFF38BDF8),
      JouffluColor.secondary100: const Color(0xFF2FA6DB),
      JouffluColor.secondaryContent: const Color(0xFF04212B),
      JouffluColor.success: const Color(0xFF34D399),
      JouffluColor.success100: const Color(0xFF2CB985),
      JouffluColor.successContent: const Color(0xFF04231A),
      JouffluColor.info: const Color(0xFF60A5FA),
      JouffluColor.info100: const Color(0xFF4B8FE0),
      JouffluColor.infoContent: const Color(0xFF06203F),
      JouffluColor.warning: const Color(0xFFFBBF24),
      JouffluColor.warning100: const Color(0xFFE0A91E),
      JouffluColor.warningContent: const Color(0xFF3A2A04),
      JouffluColor.danger: const Color(0xFFFB7185),
      JouffluColor.danger100: const Color(0xFFE05F72),
      JouffluColor.dangerContent: const Color(0xFF3A0A14),
    }),
  ),
  ThemePreset(
    'Synthwave',
    JouffluColors({
      JouffluColor.foreground: const Color(0xFFF9F7FD),
      JouffluColor.foreground100: const Color(0xFFABA7B7),
      JouffluColor.foreground200: const Color(0xFF7F798F),
      JouffluColor.border: const Color(0xFF3A2A63),
      JouffluColor.border100: const Color(0xFF2A1E4C),
      JouffluColor.background: const Color(0xFF1B1235),
      JouffluColor.background100: const Color(0xFF241A4A),
      JouffluColor.background200: const Color(0xFF2D1B69),
      JouffluColor.primary: const Color(0xFFE779C1),
      JouffluColor.primary100: const Color(0xFFC467A4),
      JouffluColor.primaryContent: const Color(0xFF2A0A20),
      JouffluColor.secondary: const Color(0xFF58C7F3),
      JouffluColor.secondary100: const Color(0xFF4BA9CF),
      JouffluColor.secondaryContent: const Color(0xFF06222E),
      JouffluColor.success: const Color(0xFF71EAD2),
      JouffluColor.success100: const Color(0xFF60C7B2),
      JouffluColor.successContent: const Color(0xFF05261F),
      JouffluColor.info: const Color(0xFF53C0F3),
      JouffluColor.info100: const Color(0xFF47A3CF),
      JouffluColor.infoContent: const Color(0xFF06222E),
      JouffluColor.warning: const Color(0xFFE2D562),
      JouffluColor.warning100: const Color(0xFFC0B553),
      JouffluColor.warningContent: const Color(0xFF2E2905),
      JouffluColor.danger: const Color(0xFFFD6F9C),
      JouffluColor.danger100: const Color(0xFFD75E85),
      JouffluColor.dangerContent: const Color(0xFF2E0716),
    }),
  ),
];
